CREATE TABLE IF NOT EXISTS HoaDon (
  MaHoaDon BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaNhanVien INT NOT NULL,
  TenNhanVienSnapshot VARCHAR(255) NOT NULL,
  UsernameNhanVienSnapshot VARCHAR(100) NULL,
  MaKhachHang INT NULL,
  TenKhachHangSnapshot VARCHAR(255) NULL,
  NgayTao DATETIME NOT NULL,
  TongTien DECIMAL(18,2) NOT NULL,
  PhuongThucThanhToan VARCHAR(50) NOT NULL,
  TrangThai VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  ReservationId BIGINT NULL,
  INDEX IDX_HoaDon_NgayTao (NgayTao),
  INDEX IDX_HoaDon_MaNhanVien (MaNhanVien),
  INDEX IDX_HoaDon_TrangThai (TrangThai)
);

CREATE TABLE IF NOT EXISTS ChiTietHoaDon (
  MaChiTiet BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaHoaDon BIGINT NOT NULL,
  MaSanPham INT NOT NULL,
  TenSanPham VARCHAR(255) NOT NULL,
  SoLuong INT NOT NULL,
  DonGia DECIMAL(18,2) NOT NULL,
  PhanTramGiam INT NOT NULL DEFAULT 0,
  GiaSauGiam DECIMAL(18,2) NOT NULL,
  GiamGia DECIMAL(18,2) NOT NULL DEFAULT 0,
  CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (MaHoaDon) REFERENCES HoaDon(MaHoaDon)
);

CREATE TABLE IF NOT EXISTS OrderOutbox (
  MaEvent BIGINT AUTO_INCREMENT PRIMARY KEY,
  EventType VARCHAR(50) NOT NULL,
  AggregateId BIGINT NOT NULL,
  PayloadJson JSON NOT NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PublishedAt DATETIME NULL
);
