CREATE TABLE IF NOT EXISTS DanhMucSanPham (
  MaDanhMuc INT AUTO_INCREMENT PRIMARY KEY,
  TenDanhMuc VARCHAR(255) NOT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS NhaCungCap (
  MaNCC INT AUTO_INCREMENT PRIMARY KEY,
  TenCongTy VARCHAR(255) NOT NULL,
  DienThoai VARCHAR(20) NOT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SanPham (
  MaSanPham INT AUTO_INCREMENT PRIMARY KEY,
  TenSanPham VARCHAR(255) NOT NULL,
  Gia DECIMAL(18,2) NOT NULL,
  SoLuong INT NOT NULL,
  MaDanhMuc INT NOT NULL,
  MaNCC INT NOT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT FK_SanPham_DanhMuc FOREIGN KEY (MaDanhMuc) REFERENCES DanhMucSanPham(MaDanhMuc),
  CONSTRAINT FK_SanPham_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

CREATE TABLE IF NOT EXISTS TBGiamGia (
  MaGiamGia INT AUTO_INCREMENT PRIMARY KEY,
  MaSanPham INT NOT NULL,
  PhanTramGiam INT NOT NULL,
  NgayTao DATE NOT NULL,
  NgayKetThuc DATE NOT NULL,
  INDEX IDX_TBGiamGia_MaSanPham_Ngay (MaSanPham, NgayTao, NgayKetThuc),
  CONSTRAINT FK_TBGiamGia_SanPham FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE IF NOT EXISTS InventoryReservation (
  MaReservation BIGINT AUTO_INCREMENT PRIMARY KEY,
  OrderRequestId VARCHAR(100) NOT NULL,
  ReservationStatus VARCHAR(30) NOT NULL,
  MaHoaDon BIGINT NULL,
  ReleaseReason VARCHAR(255) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ConfirmedAt DATETIME NULL,
  ReleasedAt DATETIME NULL,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UQ_InventoryReservation_OrderRequestId UNIQUE (OrderRequestId)
);

CREATE TABLE IF NOT EXISTS InventoryReservationItem (
  MaReservationItem BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaReservation BIGINT NOT NULL,
  MaSanPham INT NOT NULL,
  TenSanPhamSnapshot VARCHAR(255) NOT NULL,
  SoLuong INT NOT NULL,
  DonGiaSnapshot DECIMAL(18,2) NOT NULL,
  PhanTramGiamSnapshot INT NOT NULL DEFAULT 0,
  GiaSauGiamSnapshot DECIMAL(18,2) NOT NULL,
  CONSTRAINT FK_InventoryReservationItem_Reservation FOREIGN KEY (MaReservation) REFERENCES InventoryReservation(MaReservation),
  CONSTRAINT FK_InventoryReservationItem_Product FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);
