CREATE TABLE IF NOT EXISTS VaiTro (
  MaVaiTro INT AUTO_INCREMENT PRIMARY KEY,
  TenVaiTro VARCHAR(100) NOT NULL,
  CONSTRAINT UQ_VaiTro_TenVaiTro UNIQUE (TenVaiTro)
);

CREATE TABLE IF NOT EXISTS Quyen (
  MaQuyen INT AUTO_INCREMENT PRIMARY KEY,
  TenQuyen VARCHAR(100) NOT NULL,
  CONSTRAINT UQ_Quyen_TenQuyen UNIQUE (TenQuyen)
);

CREATE TABLE IF NOT EXISTS VaiTro_Quyen (
  MaVaiTro INT NOT NULL,
  MaQuyen INT NOT NULL,
  PRIMARY KEY (MaVaiTro, MaQuyen),
  CONSTRAINT FK_VaiTroQuyen_VaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro),
  CONSTRAINT FK_VaiTroQuyen_Quyen FOREIGN KEY (MaQuyen) REFERENCES Quyen(MaQuyen)
);

CREATE TABLE IF NOT EXISTS TaiKhoan (
  MaTaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  MaVaiTro INT NOT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT UQ_TaiKhoan_Username UNIQUE (Username),
  CONSTRAINT FK_TaiKhoan_VaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro)
);

CREATE TABLE IF NOT EXISTS NhanVien (
  MaNhanVien INT AUTO_INCREMENT PRIMARY KEY,
  HoTen VARCHAR(255) NOT NULL,
  DienThoai VARCHAR(20) NOT NULL,
  MaTaiKhoan INT NOT NULL,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT UQ_NhanVien_MaTaiKhoan UNIQUE (MaTaiKhoan),
  CONSTRAINT FK_NhanVien_TaiKhoan FOREIGN KEY (MaTaiKhoan) REFERENCES TaiKhoan(MaTaiKhoan)
);

CREATE TABLE IF NOT EXISTS KhachHang (
  MaKhachHang INT AUTO_INCREMENT PRIMARY KEY,
  MaKhachHangCode VARCHAR(20) NULL,
  TenKhachHang VARCHAR(255) NOT NULL,
  SoDienThoai VARCHAR(20) NOT NULL,
  DiaChi VARCHAR(255) NULL,
  DiemTichLuy INT NOT NULL DEFAULT 0,
  IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT UQ_KhachHang_MaKhachHangCode UNIQUE (MaKhachHangCode),
  CONSTRAINT UQ_KhachHang_SoDienThoai UNIQUE (SoDienThoai)
);

CREATE TABLE IF NOT EXISTS CaiDatHeThong (
  Id TINYINT PRIMARY KEY,
  TenCuaHang VARCHAR(255) NOT NULL,
  DiaChi VARCHAR(255) NOT NULL,
  SoDienThoai VARCHAR(20) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  NoiDungHoaDon VARCHAR(500) NOT NULL,
  VatPercent DECIMAL(5,2) NOT NULL DEFAULT 8.00,
  Logo VARCHAR(255) NOT NULL,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
